server:
  port: 8040

spring:
  application:
    # register name on eureka server
    name: microservice-gateway-zuul

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      # eureka server url (aware the slash in the end can't be ignored)
      defaultZone: http://localhost:8761/eureka/
  instance:
    # register IP address on eureka server (default is false, and will register host name instead)
    prefer-ip-address: true

zuul:
  routes:
    user-route:                                 # it's a name for routes. can be named by yourself
      url: http://localhost:8010/               # service url
      path: /ordersys/**                        # service-id mapping path

ribbon:
  eureka:
    enabled: false # ban eureka's ribbon. ref: http://cloud.spring.io/spring-cloud-static/Camden.SR3/#_example_disable_eureka_use_in_ribbon

application-client-consumer:
  ribbon:
    listOfServers: localhost:8010