server:
  port: 8040

spring:
  application:
    # register name on eureka server
    name: microservice-gateway-zuul

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      # eureka server url (aware the slash in the end can't be ignored)
      defaultZone: http://localhost:8761/eureka/
  instance:
    # register IP address on eureka server (default is false, and will register host name instead)
    prefer-ip-address: true

zuul:
  routes:
    application-client-consumer:
      path: /order/**
      strip-prefix: false

# Zuul will forward /order/users/1 request to /application-service-provider/users/1
logging:
  level:
    com.netflix: DEBUG