server:
  port: 8010
spring:
  application:
    # register name on eureka server
    name: application-client-consumer

eureka:
  client:
    service-url:
      # eureka server url (aware the slash in the end can't be ignored)
      defaultZone: http://localhost:8761/eureka/
  instance:
    # register IP address on eureka server (default is false, and will register host name instead)
    prefer-ip-address: true

ribbon:
  eager-load:
    enabled: true
    clients: application-service-provider