server:
  port: 8000

spring:
  application:
    # register name on eureka server
    name: application-service-provider
  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

management:
  endpoints:
    web:
      exposure:
        # access all actuator endpoints
        include: '*'
  endpoint:
    health:
      # show health check detail
      show-details: always

eureka:
  client:
    service-url:
      # eureka server url (aware the slash in the end can't be ignored)
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    # register IP address on eureka server (default is false, and will register host name instead)
    prefer-ip-address: true


